# Site
name: "Intel < M1"
title: "Intel < M1"
description: "Người chơi hệ chấp quạt. Chấp luôn cả Pin."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: https://hidb.ml
google_analytics: 'UA-46278016-1'
disqus: 'hidb-ml'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  DcQ:
    name: Đoàn Trung Quân
    display_name: DcQ
    avatar: 'assets/images/avatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: dcqbean@gmail.com
    web: https://dcqstudio.cf/
    description: "Dev Ruby on rails quèn, chuyên làm website và tools dạo."
  Andy:
    name: Andy Phạm
    display_name: Thịt Luộc
    avatar: 'assets/images/avt-andy.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    web: https://www.facebook.com/thitluoc20
    description: "Từng là admin của group Maclife và Đồng Bọn."
  Tuan:
    name: Vũ Nguyễn Anh Tuấn
    display_name: Vũ Nguyễn Anh Tuấn
    avatar: 'assets/images/avt-nvat.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    web: https://www.facebook.com/maclife.vn
    description: "Admin của group Maclife và Đồng Bọn."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
